name: Delete old workflow runs
on:
  schedule:
    - cron: '0 1 * * *'
    
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 30
         
